version: "3.2"

services:
  actionhandler:
    build:
      context: other_ahs/powershell
      dockerfile: Dockerfile
    container_name: hiro-actionhandler
    image: arago/hiro-actionhandler:v1.1.2
    # network_mode: "host"
    # ports:
    #   - "8080:8080/tcp"
    network_mode: bridge
    environment:
      - TZ=UTC
      - HIRO_USER=action_handler_username
      - HIRO_PASS=action_handler_password
      - HIRO_CLIENTID=action_handler
      - HIRO_CLIENTSECRET=action_handler_secret
      - HIRO_ENDPOINT=http://hiro-graph-mock:8081
      - HIRO_AUTH_ENDPOINT=http://hiro-graph-mock:8081
      - USE_DEFAULT_AH_CONFIGS=ExecuteCommand,HTTPRequest
      - WINRM_PASSWORD=CHANGME
      - WINRM_USERNAME=Administrator
      - AH_CONFIG=
        {"handlers":[
        {
        "name":"Windows Remote Commands",
        "capability":"ExecuteWindowsCommand",
        "implementation":"local",
        "exec":"python3 -u /scripts/windows_remote.py $${host} $${transport} $${command_type} \"$${command}\"",
        "escape_quotes": true
        }
        ]}
    volumes:
      - type: bind
        source: ssh-keys
        target: /home/hiro/.ssh
    restart: unless-stopped
    depends_on:
      - graph-mock

  graph-mock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hiro-graph-mock
    image: hexpm/elixir:1.15.5-erlang-26.0.2-ubuntu-jammy-20230126
    network_mode: bridge
    # network_mode: "host"
    # ports:
    #   - "8081:8081/tcp"
    environment:
      - "MIX_ENV=dev"
    volumes:
      - type: bind
        source: .
        target: /root/graph_conn
    restart: unless-stopped
