name: Bless the code

on:
  push: {}
  pull_request:
    branches:
      - master
env:
  MIX_ENV: test

jobs:
  graph_conn-newer-elixir:
    name: Full check for Elixir >= 1.15
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        elixir: ["1.15", "1.16"]
        erlang: ["25", "26"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ matrix.erlang }}-${{ matrix.elixir }}-deps-${{ hashFiles('mix.lock') }}-1
          restore-keys: ${{ matrix.erlang }}-${{ matrix.elixir }}-deps-
      - name: Install dependencies
        run: mix deps.get
      - name: Restore builds cache
        uses: actions/cache@v3
        with:
          path: _build/test
          key: ${{ matrix.erlang }}-${{ matrix.elixir }}-build_test--${{ hashFiles('mix.lock') }}-1
          restore-keys: ${{ matrix.erlang }}-${{ matrix.elixir }}-build_test-
      - name: Check warnings, formatting, tests and dialyzer
        run: mix bless
