name: Bless the code

on: 
  push: {}
  pull_request:
      branches:
        - master
env:
  MIX_ENV: test

jobs:
  graph_conn:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.9.4', '1.10.4', '1.11.3']
        erlang: ['22.3', '23.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.erlang }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ matrix.erlang }}-${{ matrix.elixir }}-deps-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ matrix.erlang }}-${{ matrix.elixir }}-deps-${{ hashFiles('mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Restore builds cache
      uses: actions/cache@v2
      with:
        path: _build/test
        key: ${{ matrix.erlang }}-${{ matrix.elixir }}-build_test--${{ hashFiles('mix.lock') }}
        restore-keys: ${{ matrix.erlang }}-${{ matrix.elixir }}-build_test--${{ hashFiles('mix.lock') }}
    - name: Check warnings
      run: mix compile --warnings-as-errors --force
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run tests
      run: mix coveralls.html
