name: Bless the code

on: 
  push: {}
  pull_request:
      branches:
        - master
env:
  MIX_ENV: test

jobs:
  graph_conn:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.9.4' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-deps-
    - name: Install dependencies
      run: mix deps.get
    - name: Restore builds cache
      uses: actions/cache@v2
      with:
        path: _build/test
        key: ${{ runner.os }}-build_test--${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-build_test-
    - name: Check warnings
      run: mix compile --warnings-as-errors --force
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run tests
      run: mix coveralls.html
